"""macOS installer for the Mica daemon.

Run once with sudo; afterwards launchd starts the daemon at boot as the
``_mica`` system user, with no password needed:

    sudo /usr/bin/python3 -m mica install

What install does (``--dry-run`` prints it without changing anything):

  1. creates a hidden ``_mica`` user and group (no login shell, no home)
  2. copies this package to /usr/local/libexec/mica, owned by root, and
     writes the daemon's config.json there
  3. creates the store (/Library/Mica) owned by _mica, and gives
     your user read-only access to it through an ACL entry
  4. gives _mica read-only access to your transcript folders through
     ACL entries (plus pass-through "search" on the folders above them)
  5. installs /Library/LaunchDaemons/local.mica.plist and starts it

The daemon runs under a root-owned interpreter (Apple's Python 3.9) with -I,
so nothing in your environment (PYTHONPATH, user site-packages, a conda env)
can change the code it runs.
"""

from __future__ import annotations

import grp
import os
import plistlib
import pwd
import re
import shutil
import stat as stat_mod
import subprocess
import sys
import time
from pathlib import Path

from mica import capture
from mica import store as v

SERVICE_USER = "_mica"
ADMIN_GIDS = frozenset({0, 80})  # wheel, admin
LABEL = "local.mica"
LIBEXEC_DIR = Path("/usr/local/libexec/mica")
PLIST_PATH = Path("/Library/LaunchDaemons") / f"{LABEL}.plist"
DEFAULT_PYTHON = "/usr/bin/python3"
PACKAGE_DIR = Path(__file__).resolve().parent
PACKAGE_FILES = ("__init__.py", "__main__.py", "store.py", "capture.py", "install.py")

# One inheritable entry per transcript folder. Directories get list/search;
# files created later inherit it as read (+ execute, since macOS maps
# search->execute on files; harmless for a daemon that only reads).
SOURCE_ACE = f"user:{SERVICE_USER} allow list,search,readattr,readextattr,readsecurity,file_inherit,directory_inherit"
ANCESTOR_ACE = f"user:{SERVICE_USER} allow search"

RUN_PY = '''"""Launcher for the installed mica daemon (generated by install)."""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
# -I leaves the script's own directory off sys.path; add it explicitly.
sys.path.insert(0, HERE)
from mica.__main__ import main  # noqa: E402

sys.exit(main(["daemon", "--config", os.path.join(HERE, "config.json")]))
'''


def mica_read_ace(user: str) -> str:
    return f"user:{user} allow list,search,readattr,readextattr,readsecurity,file_inherit,directory_inherit"


# ---------------------------------------------------------------------------
# Plan: a list of steps, each a description plus a command or a function
# ---------------------------------------------------------------------------
class Step:
    def __init__(self, text: str, argv=None, func=None, check: bool = True):
        self.text = text
        self.argv = argv
        self.func = func
        self.check = check

    def describe(self) -> str:
        if self.argv:
            return "  $ " + " ".join(_quote(a) for a in self.argv)
        return "  - " + self.text

    def run(self) -> None:
        if self.argv:
            subprocess.run(self.argv, check=self.check, stdout=subprocess.DEVNULL)
        else:
            self.func()


def _quote(arg: str) -> str:
    return arg if re.fullmatch(r"[A-Za-z0-9_./:=@,+-]+", arg) else "'" + arg.replace("'", "'\\''") + "'"


def _run_plan(steps: list, dry_run: bool) -> None:
    for step in steps:
        print(step.describe())
        if not dry_run:
            step.run()


# ---------------------------------------------------------------------------
# Checks
# ---------------------------------------------------------------------------
def _require_macos_root(dry_run: bool) -> None:
    if sys.platform != "darwin":
        raise SystemExit("the Mica installer currently supports macOS only")
    if os.geteuid() != 0 and not dry_run:
        raise SystemExit("run with sudo: sudo /usr/bin/python3 -m mica install")


def _target_user(name: str | None):
    name = name or os.environ.get("SUDO_USER")
    if not name or name == "root":
        raise SystemExit("could not tell whose transcripts to protect; pass --user NAME")
    try:
        return pwd.getpwnam(name)
    except KeyError:
        raise SystemExit(f"no such user: {name}")


def root_owned_chain(path: Path) -> list:
    """Problems that would let a non-root user change ``path``: any component
    from it up to / that is not owned by root or is group/world-writable."""
    problems = []
    current = Path(path)
    while True:
        try:
            st = os.stat(current)
        except OSError as exc:
            problems.append(f"{current}: {exc.strerror}")
            break
        if st.st_uid != 0:
            problems.append(f"{current} is owned by uid {st.st_uid}, not root")
        if st.st_mode & (stat_mod.S_IWGRP | stat_mod.S_IWOTH) and not (st.st_mode & stat_mod.S_ISVTX):
            problems.append(f"{current} is writable by group/others")
        if current.parent == current:
            break
        current = current.parent
    return problems


def resolve_interpreter(python: str) -> tuple:
    """(real executable, sys.prefix) of ``python``, refusing anything a
    non-root user could modify."""
    out = subprocess.run(
        [python, "-I", "-c", "import sys; print(sys.executable); print(sys.prefix); print(sys.version_info[:2] >= (3, 9))"],
        check=True, capture_output=True, text=True,
    ).stdout.split("\n")
    exe, prefix, new_enough = Path(out[0]).resolve(), Path(out[1]).resolve(), out[2] == "True"
    if not new_enough:
        raise SystemExit(f"{python} is older than Python 3.9")
    problems = root_owned_chain(exe) + root_owned_chain(prefix)
    if problems:
        raise SystemExit(
            f"refusing to run the daemon with {exe}: an agent running as you could modify it.\n  "
            + "\n  ".join(problems)
            + "\nUse Apple's /usr/bin/python3 (install the Command Line Tools if it's missing)."
        )
    return str(exe), str(prefix)


def _free_id(start: int = 300, stop: int = 500) -> int:
    used = set()
    for kind, attr in (("/Users", "UniqueID"), ("/Groups", "PrimaryGroupID")):
        out = subprocess.run(["dscl", ".", "-list", kind, attr], capture_output=True, text=True).stdout
        for line in out.splitlines():
            parts = line.split()
            if parts and parts[-1].lstrip("-").isdigit():
                used.add(int(parts[-1]))
    for candidate in range(start, stop):
        if candidate not in used:
            return candidate
    raise SystemExit("no free system uid/gid between 300 and 500")


def _service_user_exists(target_user=None) -> bool:
    """Reuse only an isolated account matching the one this installer creates.

    A name alone is not an isolation boundary: duplicate numeric IDs or
    extra group members would give other users access to the store.
    All checks are read-only and happen before confirmation or plan execution.
    """
    try:
        account = pwd.getpwnam(SERVICE_USER)
    except KeyError:
        try:
            grp.getgrnam(SERVICE_USER)
        except KeyError:
            return False
        raise SystemExit(f"refusing to overwrite existing group {SERVICE_USER}: its user is missing")

    problems = []
    if not 300 <= account.pw_uid < 500:
        problems.append("uid must be in the installer's system-account range (300–499)")
    if target_user is not None and account.pw_uid == target_user.pw_uid:
        problems.append("shares the transcript owner's uid")
    if account.pw_shell != "/usr/bin/false" or account.pw_dir != "/var/empty":
        problems.append("must have shell /usr/bin/false and home /var/empty")
    try:
        group = grp.getgrnam(SERVICE_USER)
    except KeyError:
        problems.append(f"group {SERVICE_USER} is missing")
    else:
        if group.gr_gid != account.pw_gid or group.gr_gid != account.pw_uid:
            problems.append("user and group must have the same dedicated uid/gid")
        if any(name != SERVICE_USER for name in group.gr_mem):
            problems.append("other users are members of the service group")

    try:
        users = pwd.getpwall()
        if any(p.pw_uid == account.pw_uid and p.pw_name != SERVICE_USER for p in users):
            problems.append("another account shares its uid")
        if any(p.pw_gid == account.pw_gid and p.pw_name != SERVICE_USER for p in users):
            problems.append("another account uses its primary group")
        if any(g.gr_gid == account.pw_gid and g.gr_name != SERVICE_USER for g in grp.getgrall()):
            problems.append("another group shares its gid")
        # macOS reports every local account as a member of everyone,
        # localaccounts, _lpoperator and the sharepoint groups (all nested
        # from everyone/localaccounts), so a fresh account never has only its
        # own group. Reject explicit extra memberships, and administrator
        # groups however they are reached.
        if set(os.getgrouplist(SERVICE_USER, account.pw_gid)) & ADMIN_GIDS:
            problems.append("belongs to an administrator group")
        if any(SERVICE_USER in g.gr_mem and g.gr_name != SERVICE_USER for g in grp.getgrall()):
            problems.append("belongs to groups besides its dedicated service group")
        # Password '*' alone is insufficient if a ShadowHash or other
        # authentication authority has subsequently been configured.
        result = subprocess.run(
            ["/usr/bin/dscl", "-plist", ".", "-read", f"/Users/{SERVICE_USER}"],
            check=True, capture_output=True,
        )
        attrs = plistlib.loads(result.stdout)
        expected = {
            "UniqueID": str(account.pw_uid), "PrimaryGroupID": str(account.pw_gid),
            "UserShell": "/usr/bin/false", "NFSHomeDirectory": "/var/empty", "Password": "*",
        }
        if not isinstance(attrs, dict):
            problems.append("local account metadata is not a dictionary")
        else:
            for key, value in expected.items():
                if attrs.get(f"dsAttrTypeStandard:{key}") != [value]:
                    problems.append(f"local account has unexpected {key}")
            if attrs.get("dsAttrTypeStandard:AuthenticationAuthority"):
                problems.append("has a configured authentication authority")
    except (OSError, subprocess.CalledProcessError, ValueError, plistlib.InvalidFileException):
        problems.append("could not verify account metadata and group memberships")

    if problems:
        raise SystemExit(f"refusing to reuse {SERVICE_USER}:\n  " + "\n  ".join(problems))
    return True


# ---------------------------------------------------------------------------
# ACL helpers
# ---------------------------------------------------------------------------
_ACE_LINE = re.compile(r"^\s*(\d+):\s+(\S+)\s")


def _ace_indices(path: Path, principal: str) -> list:
    """Indices of ACL entries on ``path`` naming ``principal`` (highest first,
    so removing them one by one keeps the remaining indices valid)."""
    out = subprocess.run(["ls", "-led", str(path)], capture_output=True, text=True).stdout
    hits = []
    for line in out.splitlines()[1:]:
        m = _ACE_LINE.match(line)
        if m and m.group(2) == principal:
            hits.append(int(m.group(1)))
    return sorted(hits, reverse=True)


def remove_aces(root: Path, principal: str, recursive: bool) -> None:
    paths = [root]
    if recursive and root.is_dir() and not root.is_symlink():
        for dirpath, dirnames, filenames in os.walk(root, followlinks=False):
            paths.extend(Path(dirpath) / n for n in dirnames + filenames)
    for path in paths:
        if path.is_symlink():
            continue
        for index in _ace_indices(path, principal):
            subprocess.run(["chmod", "-a#", str(index), str(path)], check=False)


def _ancestors(home: Path, root: Path) -> list:
    """Directories from ``home`` down to (not including) ``root``."""
    try:
        rel = root.relative_to(home)
    except ValueError:
        return []
    out, current = [home], home
    for part in rel.parts[:-1]:
        current = current / part
        out.append(current)
    return out


# ---------------------------------------------------------------------------
# Install
# ---------------------------------------------------------------------------
def add_install_args(ap) -> None:
    ap.add_argument("--user", help="whose transcripts to protect (default: the sudo caller)")
    ap.add_argument("--store", default=str(v.DEFAULT_STORE_DIR), help="store directory")
    ap.add_argument("--python", default=DEFAULT_PYTHON, help="root-owned Python 3.9+ for the daemon")
    ap.add_argument("--poll", type=float, default=capture.DEFAULT_POLL_SECONDS, help="seconds between polls")
    ap.add_argument("--yes", action="store_true", help="don't ask for confirmation")
    ap.add_argument("--dry-run", action="store_true", help="print the plan without changing anything")


def build_install_plan(user, store_dir: Path, python_exe: str, poll: float, service_exists: bool, free_id=None) -> tuple:
    """(steps, sources, notes) for installing for ``user`` (a pwd entry)."""
    home = Path(os.path.realpath(user.pw_dir))
    sources = capture.default_sources(home)
    notes = []
    steps = []

    if not service_exists:
        ident = str(free_id() if callable(free_id) else free_id)
        group = f"/Groups/{SERVICE_USER}"
        account = f"/Users/{SERVICE_USER}"
        steps += [
            Step("create group", ["dscl", ".", "-create", group]),
            Step("group id", ["dscl", ".", "-create", group, "PrimaryGroupID", ident]),
            Step("group name", ["dscl", ".", "-create", group, "RealName", "Mica Helper"]),
            Step("group password", ["dscl", ".", "-create", group, "Password", "*"]),
            Step("create user", ["dscl", ".", "-create", account]),
            Step("user id", ["dscl", ".", "-create", account, "UniqueID", ident]),
            Step("user group", ["dscl", ".", "-create", account, "PrimaryGroupID", ident]),
            Step("no login shell", ["dscl", ".", "-create", account, "UserShell", "/usr/bin/false"]),
            Step("no home", ["dscl", ".", "-create", account, "NFSHomeDirectory", "/var/empty"]),
            Step("user name", ["dscl", ".", "-create", account, "RealName", "Mica Helper"]),
            Step("no password", ["dscl", ".", "-create", account, "Password", "*"]),
            Step("hidden", ["dscl", ".", "-create", account, "IsHidden", "1"]),
        ]

    kept_sources = []
    for src in sources:
        if src.root.is_dir():
            kept_sources.append(src)
        elif src.root.parent.is_dir():
            # e.g. ~/.codex/archived_sessions before Codex first archives a
            # session: create it now so it carries the ACL from the start.
            kept_sources.append(src)
            steps.append(Step(f"create {src.root}", func=_mkdir_as(src.root, user)))
        else:
            notes.append(f"skipping {src.name}: {src.root.parent} does not exist (re-run install after installing it)")

    config = {
        "mica": str(store_dir),
        "poll_seconds": poll,
        "user": user.pw_name,
        "sources": [s.to_json() for s in kept_sources],
    }
    steps.append(Step(f"install daemon code to {LIBEXEC_DIR} (root-owned)", func=lambda: _install_code(config)))

    steps += [
        Step("create mica", ["mkdir", "-p", str(store_dir)]),
        Step("mica owner", ["chown", f"{SERVICE_USER}:{SERVICE_USER}", str(store_dir)]),
        Step("mica mode", ["chmod", "750", str(store_dir)]),
        Step(f"clear old mica ACL entries for {user.pw_name}",
             func=lambda: remove_aces(store_dir, f"user:{user.pw_name}", recursive=True)),
        Step(f"let {user.pw_name} read the store", ["chmod", "-R", "+a", mica_read_ace(user.pw_name), str(store_dir)]),
    ]

    ancestors = []
    for src in kept_sources:
        for d in _ancestors(home, src.root):
            if d not in ancestors:
                ancestors.append(d)
    for d in ancestors:
        steps.append(Step(f"clear old entries on {d}", func=lambda d=d: remove_aces(d, f"user:{SERVICE_USER}", False)))
        steps.append(Step(f"pass-through on {d}", ["chmod", "+a", ANCESTOR_ACE, str(d)]))
    for src in kept_sources:
        steps.append(Step(f"clear old entries under {src.root}",
                          func=lambda r=src.root: remove_aces(r, f"user:{SERVICE_USER}", True)))
        steps.append(Step(f"read access to {src.root}", ["chmod", "-R", "+a", SOURCE_ACE, str(src.root)]))

    steps += [
        Step(f"write {PLIST_PATH}", func=lambda: _write_plist(python_exe, store_dir)),
        Step("stop any running copy", ["launchctl", "bootout", f"system/{LABEL}"], check=False),
        Step("start at boot", ["launchctl", "enable", f"system/{LABEL}"]),
        Step("start now", ["launchctl", "bootstrap", "system", str(PLIST_PATH)]),
    ]
    return steps, kept_sources, notes


def _mkdir_as(path: Path, user):
    def run():
        path.mkdir(exist_ok=True)
        os.chown(path, user.pw_uid, user.pw_gid)
        os.chmod(path, 0o755)
    return run


def _install_code(config: dict) -> None:
    import json

    if LIBEXEC_DIR.exists():
        shutil.rmtree(LIBEXEC_DIR)
    pkg = LIBEXEC_DIR / "mica"
    pkg.mkdir(parents=True)
    for name in PACKAGE_FILES:
        shutil.copyfile(PACKAGE_DIR / name, pkg / name)
    (LIBEXEC_DIR / "run.py").write_text(RUN_PY, encoding="utf-8")
    (LIBEXEC_DIR / "config.json").write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
    for dirpath, dirnames, filenames in os.walk(LIBEXEC_DIR):
        os.chown(dirpath, 0, 0)
        os.chmod(dirpath, 0o755)
        for name in filenames:
            os.chown(os.path.join(dirpath, name), 0, 0)
            os.chmod(os.path.join(dirpath, name), 0o644)
    # /usr/local is user-owned on some Macs (old Homebrew installs); if any
    # parent is, an agent could swap the daemon's code, so refuse.
    problems = root_owned_chain(LIBEXEC_DIR / "run.py")
    if problems:
        shutil.rmtree(LIBEXEC_DIR, ignore_errors=True)
        raise SystemExit("installed code would not be protected:\n  " + "\n  ".join(problems))


def plist_dict(python_exe: str, store_dir: Path) -> dict:
    return {
        "Label": LABEL,
        "ProgramArguments": [python_exe, "-I", "-B", str(LIBEXEC_DIR / "run.py")],
        "UserName": SERVICE_USER,
        "GroupName": SERVICE_USER,
        "RunAtLoad": True,
        "KeepAlive": True,
        "ProcessType": "Background",
        "LowPriorityIO": True,
        "Nice": 10,
        "Umask": 0o027,
        "WorkingDirectory": str(LIBEXEC_DIR),
        "EnvironmentVariables": {"HOME": "/var/empty"},
        "StandardOutPath": str(store_dir / "daemon.log"),
        "StandardErrorPath": str(store_dir / "daemon.log"),
    }


def _write_plist(python_exe: str, store_dir: Path) -> None:
    with open(PLIST_PATH, "wb") as fh:
        plistlib.dump(plist_dict(python_exe, store_dir), fh)
    os.chown(PLIST_PATH, 0, 0)
    os.chmod(PLIST_PATH, 0o644)


def _confirm(prompt: str) -> bool:
    try:
        return input(prompt + " [y/N] ").strip().lower() in ("y", "yes")
    except EOFError:
        return False


def cmd_install(args) -> int:
    _require_macos_root(args.dry_run)
    user = _target_user(args.user)
    service_exists = _service_user_exists(user)
    store_dir = Path(args.store)
    existing = store_dir.parent
    while not existing.exists():
        existing = existing.parent
    problems = root_owned_chain(existing)
    if problems:
        raise SystemExit(
            f"refusing mica location {store_dir}: a folder above it is not root-owned, so an agent "
            "could move the store aside.\n  " + "\n  ".join(problems)
        )
    python_exe, _prefix = resolve_interpreter(args.python)
    steps, sources, notes = build_install_plan(
        user, store_dir, python_exe, args.poll, service_exists, free_id=_free_id,
    )
    print(f"Mica install for {user.pw_name}")
    print(f"  daemon user:   {SERVICE_USER}")
    print(f"  interpreter:   {python_exe}")
    print(f"  store:         {store_dir}")
    for src in sources:
        print(f"  capture:       {src.root}")
    for note in notes:
        print(f"  note: {note}")
    print()
    if args.dry_run:
        print("Plan (dry run, nothing changed):")
        _run_plan(steps, dry_run=True)
        return 0
    if not args.yes and not _confirm("Proceed?"):
        print("aborted")
        return 1
    _run_plan(steps, dry_run=False)
    print("\nwaiting for the first heartbeat…")
    reader = v.StoreReader(store_dir)
    for _ in range(40):
        if reader.available() and reader.status()["running"]:
            status = reader.status()
            print(f"running: {status['n_files']} transcripts captured so far.")
            print(f"Point the viewer at it (it finds {v.DEFAULT_STORE_DIR} automatically).")
            return 0
        time.sleep(0.5)
    print(f"no heartbeat yet; check {store_dir / 'daemon.log'} and `launchctl print system/{LABEL}`")
    return 1


# ---------------------------------------------------------------------------
# Uninstall
# ---------------------------------------------------------------------------
def add_uninstall_args(ap) -> None:
    ap.add_argument("--user", help="whose transcript folders carry the ACL entries (default: the sudo caller)")
    ap.add_argument("--store", default=str(v.DEFAULT_STORE_DIR))
    ap.add_argument("--delete-store", action="store_true",
                    help="also delete every captured transcript (default: keep them, owned by root)")
    ap.add_argument("--yes", action="store_true")
    ap.add_argument("--dry-run", action="store_true")


def build_uninstall_plan(user, store_dir: Path, delete_store: bool) -> list:
    home = Path(os.path.realpath(user.pw_dir))
    sources = capture.default_sources(home)
    steps = [
        Step("stop the daemon", ["launchctl", "bootout", f"system/{LABEL}"], check=False),
        Step(f"remove {PLIST_PATH}", ["rm", "-f", str(PLIST_PATH)]),
        Step(f"remove {LIBEXEC_DIR}", ["rm", "-rf", str(LIBEXEC_DIR)]),
    ]
    ancestors = []
    for src in sources:
        steps.append(Step(f"remove {SERVICE_USER} ACL entries under {src.root}",
                          func=lambda r=src.root: remove_aces(r, f"user:{SERVICE_USER}", True)))
        for d in _ancestors(home, src.root):
            if d not in ancestors:
                ancestors.append(d)
    for d in ancestors:
        steps.append(Step(f"remove pass-through on {d}", func=lambda d=d: remove_aces(d, f"user:{SERVICE_USER}", False)))
    if delete_store:
        steps.append(Step(f"delete {store_dir}", ["rm", "-rf", str(store_dir)]))
    else:
        steps.append(Step(f"keep {store_dir}, owned by root", ["chown", "-R", "root:wheel", str(store_dir)], check=False))
    steps += [
        Step("delete user", ["dscl", ".", "-delete", f"/Users/{SERVICE_USER}"], check=False),
        Step("delete group", ["dscl", ".", "-delete", f"/Groups/{SERVICE_USER}"], check=False),
    ]
    return steps


def cmd_uninstall(args) -> int:
    _require_macos_root(args.dry_run)
    user = _target_user(args.user)
    steps = build_uninstall_plan(user, Path(args.store), args.delete_store)
    if args.dry_run:
        print("Plan (dry run, nothing changed):")
        _run_plan(steps, dry_run=True)
        return 0
    what = "and DELETE all captured transcripts" if args.delete_store else "(captured transcripts are kept)"
    if not args.yes and not _confirm(f"Uninstall Mica {what}?"):
        print("aborted")
        return 1
    _run_plan(steps, dry_run=False)
    print("uninstalled")
    return 0
